#include "../src/common.cpp"
#include "../src/errors.cpp"
#include "../src/lib.cpp"
#include "../src/mainwindow.cpp"
#include "../src/main.cpp"
#include "../src/tabs.cpp"
#include "../src/opendialog.cpp"
#include "../src/otherwindow.cpp"
